version: '2.1'

services:
    pytorch:
        build:
            context: ./cuda-9.1
            dockerfile: Dockerfile
        image: huangyingw/pytorch
        environment:
            - FILENAME="~/.bashrc"
        volumes:
            - ./.jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
            - ./.jupyter/jupyter_notebook_config.json:/root/.jupyter/jupyter_notebook_config.json
            - ./.jupyter/custom/custom.js:/root/.jupyter/custom/custom.js
            - ./var/logs/:/var/logs/
        ports:  
            - "8888:8888"
        command: /bin/sh -c "/entrypoint.sh"
